/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Blind API
 * kood/Jõhvi match-me task API
 * OpenAPI spec version: v0.0.1
 */

export interface AccountSettingsRequestDTO {
  /**
   * @minLength 0
   * @maxLength 320
   * @pattern ^[^\s@]+@[^\s@]+\.[^\s@]+$
   */
  email: string;
  number: string;
}
