/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Blind API
 * kood/Jõhvi match-me task API
 * OpenAPI spec version: v0.0.1
 */
import type { ActivityLogType } from './activityLogType';
import type { User } from './user';

export interface ActivityLog {
  id?: number;
  user: User;
  type?: ActivityLogType;
  instant: string;
}
