/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Blind API
 * kood/Jõhvi match-me task API
 * OpenAPI spec version: v0.0.1
 */

export interface AttributesSettingsRequestDTO {
  birth_date: string;
  /**
   * @minLength 2
   * @maxLength 100
   */
  city: string;
  /** @minimum 1 */
  gender_self: number;
  /**
   * @minimum -90
   * @maximum 90
   */
  latitude?: number;
  /**
   * @minimum -180
   * @maximum 180
   */
  longitude?: number;
}
