/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Blind API
 * kood/Jõhvi match-me task API
 * OpenAPI spec version: v0.0.1
 */
import type { RecommendedUserDTO } from './recommendedUserDTO';

export interface BatchUserResponseDTO {
  users?: RecommendedUserDTO[];
}
