/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Blind API
 * kood/Jõhvi match-me task API
 * OpenAPI spec version: v0.0.1
 */
import type { GenderTypeDTO } from './genderTypeDTO';

export interface BiographicalResponseDTO {
  gender_self?: GenderTypeDTO;
  gender_other?: GenderTypeDTO;
  hobbies?: number[];
  age_self?: number;
  age_min?: number;
  age_max?: number;
  distance?: number;
  probability_tolerance?: number;
}
