/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Blind API
 * kood/Jõhvi match-me task API
 * OpenAPI spec version: v0.0.1
 */

export interface ChatPreviewResponseDTO {
  connectedUserAlias?: string;
  connectedUserFirstName?: string;
  connectedUserId?: number;
  connectedUserLastName?: string;
  connectedUserProfilePicture?: string;
  connectionId?: number;
  lastMessageContent?: string;
  lastMessageTimestamp?: string;
  unreadMessageCount?: number;
}
