/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Blind API
 * kood/Jõhvi match-me task API
 * OpenAPI spec version: v0.0.1
 */
import type { MessageEventDTO } from './messageEventDTO';

export interface ChatMessageResponseDTO {
  messageId: number;
  connectionId: number;
  senderId: number;
  senderAlias: string;
  content: string;
  createdAt: string;
  event: MessageEventDTO;
}
