/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Blind API
 * kood/Jõhvi match-me task API
 * OpenAPI spec version: v0.0.1
 */
import type { MessageEventDTO } from './messageEventDTO';

export interface ChatMessageResponseDTO {
  connectionId: number;
  content: string;
  createdAt: string;
  event: MessageEventDTO;
  messageId: number;
  senderAlias: string;
  senderId: number;
}
