/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Blind API
 * kood/Jõhvi match-me task API
 * OpenAPI spec version: v0.0.1
 */
import type { Connection } from './connection';
import type { ConnectionStatus } from './connectionStatus';
import type { ConnectionType } from './connectionType';
import type { User } from './user';

export interface ConnectionState {
  id?: number;
  connection: Connection;
  user: User;
  connection_type?: ConnectionType;
  timestamp: string;
  status?: ConnectionStatus;
  requesterId?: number;
  targetId?: number;
}
