/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Blind API
 * kood/Jõhvi match-me task API
 * OpenAPI spec version: v0.0.1
 */
import type { Connection } from './connection';
import type { UserScore } from './userScore';

export interface ConnectionResult {
  id?: number;
  userScores?: UserScore;
  connection?: Connection;
  scoreAfter?: number;
  blindAfter?: number;
  vibeAfter?: number;
}
