/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Blind API
 * kood/Jõhvi match-me task API
 * OpenAPI spec version: v0.0.1
 */

export type ConnectionStatus = (typeof ConnectionStatus)[keyof typeof ConnectionStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ConnectionStatus = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  DISCONNECTED: 'DISCONNECTED',
} as const;
