/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Blind API
 * kood/Jõhvi match-me task API
 * OpenAPI spec version: v0.0.1
 */
import type { ConnectionResult } from './connectionResult';
import type { ConnectionState } from './connectionState';
import type { UserMessage } from './userMessage';
import type { User } from './user';

export interface Connection {
  connectionResults?: ConnectionResult[];
  connectionStates?: ConnectionState[];
  id?: number;
  userMessages?: UserMessage[];
  users?: User[];
}
