/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Blind API
 * kood/Jõhvi match-me task API
 * OpenAPI spec version: v0.0.1
 */
import type { HobbyResponseDTO } from './hobbyResponseDTO';
import type { UserRoleType } from './userRoleType';
import type { UserState } from './userState';

export interface CurrentUserResponseDTO {
  id: number;
  email: string;
  firstName: string;
  lastName: string;
  alias?: string;
  aboutMe?: string;
  hobbies?: HobbyResponseDTO[];
  profilePicture?: string;
  role?: UserRoleType[];
  profileLink?: string;
  state?: UserState;
}
