/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Blind API
 * kood/Jõhvi match-me task API
 * OpenAPI spec version: v0.0.1
 */
import type { MessageEventType } from './messageEventType';
import type { UserMessage } from './userMessage';

export interface MessageEvent {
  id?: number;
  message: UserMessage;
  messageEventType?: MessageEventType;
  timestamp: string;
}
