/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Blind API
 * kood/Jõhvi match-me task API
 * OpenAPI spec version: v0.0.1
 */

export type MessageEventTypeEnum = (typeof MessageEventTypeEnum)[keyof typeof MessageEventTypeEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MessageEventTypeEnum = {
  SENT: 'SENT',
  RECEIVED: 'RECEIVED',
  READ: 'READ',
} as const;
