/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Blind API
 * kood/Jõhvi match-me task API
 * OpenAPI spec version: v0.0.1
 */
import type { UserMessage } from './userMessage';
import type { MessageEventType } from './messageEventType';

export interface MessageEvent {
    id?: number;
    message: UserMessage;
    messageEventType?: MessageEventType;
    timestamp: string;
}
