/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Blind API
 * kood/Jõhvi match-me task API
 * OpenAPI spec version: v0.0.1
 */
import type { MessageEventTypeEnum } from './messageEventTypeEnum';

export interface MessageEventDTO {
  type: MessageEventTypeEnum;
  timestamp: string;
}
