/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Blind API
 * kood/Jõhvi match-me task API
 * OpenAPI spec version: v0.0.1
 */
import type { ChatMessageResponseDTO } from './chatMessageResponseDTO';
import type { Pageablenull } from './pageablenull';
import type { Sortnull } from './sortnull';

export interface PageChatMessageResponseDTO {
  totalPages?: number;
  totalElements?: number;
  first?: boolean;
  last?: boolean;
  size?: number;
  content?: ChatMessageResponseDTO[];
  number?: number;
  sort?: Sortnull;
  pageable?: Pageablenull;
  numberOfElements?: number;
  empty?: boolean;
}
