/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Blind API
 * kood/Jõhvi match-me task API
 * OpenAPI spec version: v0.0.1
 */

export interface Pageable {
    /** @minimum 0 */
    page?: number;
    /** @minimum 1 */
    size?: number;
    sort?: string[];
}
