/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Blind API
 * kood/Jõhvi match-me task API
 * OpenAPI spec version: v0.0.1
 */
import type { Sortnull } from './sortnull';

export interface Pageablenull {
    offset?: number;
    paged?: boolean;
    pageNumber?: number;
    pageSize?: number;
    sort?: Sortnull;
    unpaged?: boolean;
}
