/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Blind API
 * kood/Jõhvi match-me task API
 * OpenAPI spec version: v0.0.1
 */
import type { PreferenceChangeType } from './preferenceChangeType';
import type { UserPreferences } from './userPreferences';

export interface PreferenceChange {
    content?: string;
    id?: number;
    instant: string;
    type?: PreferenceChangeType;
    userPreferences: UserPreferences;
}
