/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Blind API
 * kood/Jõhvi match-me task API
 * OpenAPI spec version: v0.0.1
 */
import type { UserGenderEnum } from './userGenderEnum';

export interface PreferencesSettingsRequestDTO {
  gender_other: UserGenderEnum;
  /**
   * @minimum 18
   * @maximum 120
   */
  age_min: number;
  /**
   * @minimum 18
   * @maximum 120
   */
  age_max: number;
  /**
   * @minimum 50
   * @maximum 300
   */
  distance: number;
  /**
   * @minimum 0
   * @maximum 1
   */
  probability_tolerance: number;
}
