/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Blind API
 * kood/Jõhvi match-me task API
 * OpenAPI spec version: v0.0.1
 */
import type { ProfileChangeType } from './profileChangeType';
import type { UserAttributes } from './userAttributes';
import type { UserProfile } from './userProfile';

export interface ProfileChange {
    content?: string;
    id?: number;
    instant: string;
    type?: ProfileChangeType;
    userAttributes?: UserAttributes;
    userProfile: UserProfile;
}
