/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Blind API
 * kood/Jõhvi match-me task API
 * OpenAPI spec version: v0.0.1
 */
import type { HobbyResponseDTO } from './hobbyResponseDTO';

export interface ProfileResponseDTO {
  firstName?: string;
  lastName?: string;
  alias?: string;
  city?: string;
  hobbies?: HobbyResponseDTO[];
  aboutMe?: string;
  profilePicture?: string;
}
