/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Blind API
 * kood/Jõhvi match-me task API
 * OpenAPI spec version: v0.0.1
 */

export interface ProfileSettingsRequestDTO {
    /**
     * @minLength 2
     * @maxLength 30
     * @pattern ^[a-zA-Z0-9\s-_]+$
     */
    alias?: string;
    /**
     * @minLength 2
     * @maxLength 50
     * @pattern ^[a-zA-Z\s-']+$
     */
    first_name: string;
    /**
     * @minLength 2
     * @maxLength 50
     * @pattern ^[a-zA-Z\s-']+$
     */
    last_name: string;
}
