/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Blind API
 * kood/Jõhvi match-me task API
 * OpenAPI spec version: v0.0.1
 */

export interface RecommendedUserDTO {
  userId: number;
  firstName: string;
  lastName: string;
  profilePicture?: string;
  age: number;
  gender: string;
  distance: number;
  hobbies?: string[];
  probability: number;
  connectionStatus?: string;
  connectionId?: number;
}
