/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Blind API
 * kood/Jõhvi match-me task API
 * OpenAPI spec version: v0.0.1
 */

export interface RecommendedUserDTO {
  age?: number;
  distance?: number;
  firstName?: string;
  gender?: string;
  hobbies?: string[];
  lastName?: string;
  probability?: number;
  profilePicture?: string;
  userId?: number;
}
