/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Blind API
 * kood/Jõhvi match-me task API
 * OpenAPI spec version: v0.0.1
 */

export interface SettingsResponseDTO {
  email?: string;
  number?: string;
  firstName?: string;
  lastName?: string;
  alias?: string;
  hobbies?: number[];
  genderSelf?: number;
  birthDate?: string;
  city?: string;
  longitude?: number;
  latitude?: number;
  genderOther?: number;
  ageMin?: number;
  ageMax?: number;
  distance?: number;
  probabilityTolerance?: number;
  profilePicture?: string;
}
