/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Blind API
 * kood/Jõhvi match-me task API
 * OpenAPI spec version: v0.0.1
 */

export interface SettingsResponseDTO {
    ageMax?: number;
    ageMin?: number;
    alias?: string;
    birthDate?: string;
    city?: string;
    distance?: number;
    email?: string;
    firstName?: string;
    genderOther?: number;
    genderSelf?: number;
    lastName?: string;
    latitude?: number;
    longitude?: number;
    number?: string;
    probabilityTolerance?: number;
}
