/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Blind API
 * kood/Jõhvi match-me task API
 * OpenAPI spec version: v0.0.1
 */

export interface SignupRequestDTO {
  /**
   * @minLength 0
   * @maxLength 320
   */
  email: string;
  /**
   * @minLength 0
   * @maxLength 20
   */
  number: string;
  /**
   * @minLength 6
   * @maxLength 40
   */
  password: string;
}
