/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Blind API
 * kood/Jõhvi match-me task API
 * OpenAPI spec version: v0.0.1
 */
import type { UserParametersRequestDTO } from './userParametersRequestDTO';

export interface UserParametersWithEmailsDTO {
  emails?: string[];
  parameters?: UserParametersRequestDTO[];
}
