/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Blind API
 * kood/Jõhvi match-me task API
 * OpenAPI spec version: v0.0.1
 */
import type { UserGenderType } from './userGenderType';
import type { PreferenceChange } from './preferenceChange';
import type { UserProfile } from './userProfile';

export interface UserPreferences {
    age_max?: number;
    age_min?: number;
    distance?: number;
    gender?: UserGenderType;
    id?: number;
    preferenceChangeLog?: PreferenceChange[];
    probability_tolerance?: number;
    userProfile?: UserProfile;
}
