/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Blind API
 * kood/Jõhvi match-me task API
 * OpenAPI spec version: v0.0.1
 */
import type { ConnectionResult } from './connectionResult';
import type { User } from './user';

export interface UserScore {
  id?: number;
  user?: User;
  currentScore?: number;
  vibeProbability?: number;
  currentBlind?: number;
  results?: ConnectionResult[];
}
