/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Blind API
 * kood/Jõhvi match-me task API
 * OpenAPI spec version: v0.0.1
 */
import type { PreferenceChange } from './preferenceChange';
import type { UserGenderType } from './userGenderType';
import type { UserProfile } from './userProfile';

export interface UserPreferences {
  id?: number;
  userProfile?: UserProfile;
  gender?: UserGenderType;
  ageMin?: number;
  ageMax?: number;
  distance?: number;
  probabilityTolerance?: number;
  preferenceChangeLog?: PreferenceChange[];
}
