/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Blind API
 * kood/Jõhvi match-me task API
 * OpenAPI spec version: v0.0.1
 */
import type { PreferenceChange } from './preferenceChange';
import type { UserGenderType } from './userGenderType';
import type { UserProfile } from './userProfile';

export interface UserPreferences {
  ageMax?: number;
  ageMin?: number;
  distance?: number;
  gender?: UserGenderType;
  id?: number;
  preferenceChangeLog?: PreferenceChange[];
  probabilityTolerance?: number;
  userProfile?: UserProfile;
}
