/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Blind API
 * kood/Jõhvi match-me task API
 * OpenAPI spec version: v0.0.1
 */

export type UserState = (typeof UserState)[keyof typeof UserState];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserState = {
  NEW: 'NEW',
  UNVERIFIED: 'UNVERIFIED',
  PROFILE_INCOMPLETE: 'PROFILE_INCOMPLETE',
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  DORMANT: 'DORMANT',
  DISABLED: 'DISABLED',
  PENDING: 'PENDING',
  VERIFIED: 'VERIFIED',
} as const;
