/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Blind API
 * kood/Jõhvi match-me task API
 * OpenAPI spec version: v0.0.1
 */

export interface UserParametersRequestDTO {
  /**
   * @minLength 2
   * @maxLength 50
   * @pattern ^[a-zA-Z\s-']+$
   */
  first_name: string;
  /**
   * @minLength 2
   * @maxLength 50
   * @pattern ^[a-zA-Z\s-']+$
   */
  last_name: string;
  /**
   * @minLength 2
   * @maxLength 30
   * @pattern ^[a-zA-Z0-9\s-_]+$
   */
  alias?: string;
  /**
   * @minItems 0
   * @maxItems 5
   */
  hobbies?: number[];
  /** @minimum 1 */
  gender_self: number;
  birth_date: string;
  /**
   * @minLength 2
   * @maxLength 100
   */
  city: string;
  /**
   * @minimum -180
   * @maximum 180
   */
  longitude?: number;
  /**
   * @minimum -90
   * @maximum 90
   */
  latitude?: number;
  /** @minimum 1 */
  gender_other: number;
  /**
   * @minimum 18
   * @maximum 120
   */
  age_min: number;
  /**
   * @minimum 18
   * @maximum 120
   */
  age_max: number;
  /**
   * @minimum 50
   * @maximum 300
   */
  distance: number;
  /**
   * @minimum 0.1
   * @maximum 1
   */
  probability_tolerance: number;
}
