/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Blind API
 * kood/Jõhvi match-me task API
 * OpenAPI spec version: v0.0.1
 */
import type { Hobby } from './hobby';
import type { ProfileChange } from './profileChange';
import type { User } from './user';
import type { UserAttributes } from './userAttributes';
import type { UserPreferences } from './userPreferences';

export interface UserProfile {
  id?: number;
  user?: User;
  preferences?: UserPreferences;
  attributes?: UserAttributes;
  profileChangeLog?: ProfileChange[];
  first_name?: string;
  last_name?: string;
  alias?: string;
  city?: string;
  profilePicture?: string;
  aboutMe?: string;
  hobbies?: Hobby[];
}
