/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Blind API
 * kood/Jõhvi match-me task API
 * OpenAPI spec version: v0.0.1
 */
import type { ProfileChange } from './profileChange';
import type { UserGenderType } from './userGenderType';
import type { UserProfile } from './userProfile';

export interface UserAttributes {
  attributeChangeLog?: ProfileChange[];
  birthdate?: string;
  gender?: UserGenderType;
  id?: number;
  location?: number[];
  userProfile?: UserProfile;
}
