/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Blind API
 * kood/Jõhvi match-me task API
 * OpenAPI spec version: v0.0.1
 */
import type { ActivityLog } from './activityLog';
import type { UserAuth } from './userAuth';
import type { UserProfile } from './userProfile';
import type { UserRoleType } from './userRoleType';
import type { UserScore } from './userScore';
import type { UserState } from './userState';

export interface User {
  activity?: ActivityLog[];
  /**
   * @minLength 0
   * @maxLength 50
   */
  email: string;
  id?: number;
  /**
   * @minLength 0
   * @maxLength 20
   */
  number?: string;
  profile?: UserProfile;
  role?: UserRoleType;
  roles?: UserRoleType[];
  score?: UserScore;
  state?: UserState;
  userAuth?: UserAuth;
}
