/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Blind API
 * kood/Jõhvi match-me task API
 * OpenAPI spec version: v0.0.1
 */
import type { ConnectionResult } from './connectionResult';
import type { User } from './user';

export interface UserScore {
    currentBlind?: number;
    currentScore?: number;
    id?: number;
    results?: ConnectionResult[];
    user?: User;
    vibeProbability?: number;
}
