/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Blind API
 * kood/Jõhvi match-me task API
 * OpenAPI spec version: v0.0.1
 */

export type UserGenderEnum = (typeof UserGenderEnum)[keyof typeof UserGenderEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserGenderEnum = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
  OTHER: 'OTHER',
} as const;
