/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Blind API
 * kood/Jõhvi match-me task API
 * OpenAPI spec version: v0.0.1
 */
import type { User } from './user';

export interface UserRoleType {
  id?: number;
  name?: string;
  users?: User[];
}
