/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Blind API
 * kood/Jõhvi match-me task API
 * OpenAPI spec version: v0.0.1
 */
import type { Connection } from './connection';
import type { MessageEvent } from './messageEvent';
import type { User } from './user';

export interface UserMessage {
    connection: Connection;
    content: string;
    createdAt?: string;
    id?: number;
    messageEvents?: MessageEvent[];
    user: User;
}
