version: '3.8'

services:
  # =============== POSTGRES DATABASE ===============
  db:
    image: postgres:15-alpine
    container_name: matchme-db
    env_file:
      - .env    # Contains POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB, etc.
    ports:
      - "5432:5432"
    networks:
      - matchme-network

  # =============== BACK-END (Spring Boot) ===============
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: matchme-backend
    env_file:
      - .env
    environment:
      # Example: override or pass environment variables to Spring Boot
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/match
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}

      # For your "application.properties" usage:
      - SPRING_PROFILES_ACTIVE=prod  # optional, if you have a "prod" profile
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - matchme-network

  # =============== FRONT-END (React) ===============
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
      args:
        VITE_GEOAPI_BASE_URL: ${VITE_GEOAPI_BASE_URL}
        VITE_GEOAPI_KEY: ${VITE_GEOAPI_KEY}
        VITE_MAX_AVATAR_SIZE_MB: ${VITE_MAX_AVATAR_SIZE_MB}
    container_name: matchme-frontend
    env_file:
      - .env
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - matchme-network

networks:
  matchme-network:
    driver: bridge
