/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Blind API
 * kood/Jõhvi match-me task API
 * OpenAPI spec version: v0.0.1
 */
import { customInstance } from '../lib/custom-axios-instance';
import type { JwtResponseDTO, LoginRequestDTO, SignupRequestDTO } from './types';

export const getAuthController = () => {
  const registerUser = (signupRequestDTO: SignupRequestDTO) => {
    return customInstance<void>({
      url: `http://localhost:8000/api/auth/signup`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: signupRequestDTO,
    });
  };
  const authenticateUser = (loginRequestDTO: LoginRequestDTO) => {
    return customInstance<JwtResponseDTO>({
      url: `http://localhost:8000/api/auth/signin`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: loginRequestDTO,
    });
  };
  return { registerUser, authenticateUser };
};
export type RegisterUserResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuthController>['registerUser']>>>;
export type AuthenticateUserResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuthController>['authenticateUser']>>
>;
