/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Blind API
 * kood/Jõhvi match-me task API
 * OpenAPI spec version: v0.0.1
 */
import { customInstance } from '../lib/custom-axios-instance';
import type { BiographicalResponseDTO, CurrentUserResponseDTO, ProfileResponseDTO, SettingsResponseDTO } from './types';

export const getMeController = () => {
  const getCurrentUser = () => {
    return customInstance<CurrentUserResponseDTO>({ url: `http://localhost:8000/api/me`, method: 'GET' });
  };
  const getParameters = () => {
    return customInstance<SettingsResponseDTO>({ url: `http://localhost:8000/api/me/settings`, method: 'GET' });
  };
  const getCurrentProfile = () => {
    return customInstance<ProfileResponseDTO>({ url: `http://localhost:8000/api/me/profile`, method: 'GET' });
  };
  const getCurrentBio = () => {
    return customInstance<BiographicalResponseDTO>({ url: `http://localhost:8000/api/me/bio`, method: 'GET' });
  };
  return { getCurrentUser, getParameters, getCurrentProfile, getCurrentBio };
};
export type GetCurrentUserResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getMeController>['getCurrentUser']>>
>;
export type GetParametersResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMeController>['getParameters']>>>;
export type GetCurrentProfileResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getMeController>['getCurrentProfile']>>
>;
export type GetCurrentBioResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMeController>['getCurrentBio']>>>;
