/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Blind API
 * kood/Jõhvi match-me task API
 * OpenAPI spec version: v0.0.1
 */
import { customInstance } from '../lib/custom-axios-instance';
import type { GenderTypeDTO } from './types';

export const getUserGenderTypeController = () => {
  const getAllGenders = () => {
    return customInstance<GenderTypeDTO[]>({ url: `http://localhost:8000/api/genders`, method: 'GET' });
  };
  return { getAllGenders };
};
export type GetAllGendersResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUserGenderTypeController>['getAllGenders']>>
>;
