/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Blind API
 * kood/Jõhvi match-me task API
 * OpenAPI spec version: v0.0.1
 */
import * as axios from 'axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';
import type {
  AccountSettingsRequestDTO,
  AttributesSettingsRequestDTO,
  BiographicalResponseDTO,
  CurrentUserResponseDTO,
  PreferencesSettingsRequestDTO,
  ProfilePictureSettingsRequestDTO,
  ProfileResponseDTO,
  ProfileSettingsRequestDTO,
  UserParametersRequestDTO,
  VerifyAccountParams,
} from './types';

export const getUserController = () => {
  const updateProfile = <TData = AxiosResponse<void>>(
    profileSettingsRequestDTO: ProfileSettingsRequestDTO,
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.default.put(`http://localhost:8000/api/users/settings/profile`, profileSettingsRequestDTO, options);
  };
  const updatePreferences = <TData = AxiosResponse<void>>(
    preferencesSettingsRequestDTO: PreferencesSettingsRequestDTO,
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.default.put(
      `http://localhost:8000/api/users/settings/preferences`,
      preferencesSettingsRequestDTO,
      options
    );
  };
  const updateAttributes = <TData = AxiosResponse<void>>(
    attributesSettingsRequestDTO: AttributesSettingsRequestDTO,
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.default.put(
      `http://localhost:8000/api/users/settings/attributes`,
      attributesSettingsRequestDTO,
      options
    );
  };
  const updateAccount = <TData = AxiosResponse<void>>(
    accountSettingsRequestDTO: AccountSettingsRequestDTO,
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.default.put(`http://localhost:8000/api/users/settings/account`, accountSettingsRequestDTO, options);
  };
  const uploadProfilePicture = <TData = AxiosResponse<void>>(
    profilePictureSettingsRequestDTO: ProfilePictureSettingsRequestDTO,
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.default.post(
      `http://localhost:8000/api/users/profile-picture`,
      profilePictureSettingsRequestDTO,
      options
    );
  };
  const verifyAccount = <TData = AxiosResponse<void>>(
    userId: number,
    params: VerifyAccountParams,
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.default.patch(`http://localhost:8000/api/users/verify/${userId}`, undefined, {
      ...options,
      params: { ...params, ...options?.params },
    });
  };
  const setParameters = <TData = AxiosResponse<void>>(
    userParametersRequestDTO: UserParametersRequestDTO,
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.default.patch(
      `http://localhost:8000/api/users/complete-registration`,
      userParametersRequestDTO,
      options
    );
  };
  const getUser = <TData = AxiosResponse<CurrentUserResponseDTO>>(
    targetId: number,
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.default.get(`http://localhost:8000/api/users/${targetId}`, options);
  };
  const getProfile = <TData = AxiosResponse<ProfileResponseDTO>>(
    targetId: number,
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.default.get(`http://localhost:8000/api/users/${targetId}/profile`, options);
  };
  const getBio = <TData = AxiosResponse<BiographicalResponseDTO>>(
    targetId: number,
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.default.get(`http://localhost:8000/api/users/${targetId}/bio`, options);
  };
  return {
    updateProfile,
    updatePreferences,
    updateAttributes,
    updateAccount,
    uploadProfilePicture,
    verifyAccount,
    setParameters,
    getUser,
    getProfile,
    getBio,
  };
};
export type UpdateProfileResult = AxiosResponse<void>;
export type UpdatePreferencesResult = AxiosResponse<void>;
export type UpdateAttributesResult = AxiosResponse<void>;
export type UpdateAccountResult = AxiosResponse<void>;
export type UploadProfilePictureResult = AxiosResponse<void>;
export type VerifyAccountResult = AxiosResponse<void>;
export type SetParametersResult = AxiosResponse<void>;
export type GetUserResult = AxiosResponse<CurrentUserResponseDTO>;
export type GetProfileResult = AxiosResponse<ProfileResponseDTO>;
export type GetBioResult = AxiosResponse<BiographicalResponseDTO>;
