export enum ConnectionUpdateType {
    NEW_REQUEST = 'NEW_REQUEST',
    REQUEST_SENT = 'REQUEST_SENT',
    REQUEST_ACCEPTED = 'REQUEST_ACCEPTED',
    REQUEST_REJECTED = 'REQUEST_REJECTED',
    DISCONNECTED = 'DISCONNECTED',
}