export const genders = [
  { label: 'Abimegender', value: 'abimegender' },
  { label: 'Adamasgender', value: 'adamasgender' },
  { label: 'Aerogender', value: 'aerogender' },
  { label: 'Aesthetigender', value: 'aesthetigender' },
  { label: 'Affectugender', value: 'affectugender' },
  { label: 'Agender', value: 'agender' },
  { label: 'Agenderflux', value: 'agenderflux' },
  { label: 'Alexigender', value: 'alexigender' },
  { label: 'Aliusgender', value: 'aliusgender' },
  { label: 'Amaregender', value: 'amaregender' },
  { label: 'Ambigender', value: 'ambigender' },
  { label: 'Ambonec', value: 'ambonec' },
  { label: 'Amicagender', value: 'amicagender' },
  { label: 'Androgyne', value: 'androgyne' },
  { label: 'Androgynous', value: 'androgynous' },
  { label: 'Anesigender', value: 'anesigender' },
  { label: 'Angenital', value: 'angenital' },
  { label: 'Anogender', value: 'anogender' },
  { label: 'Anongender', value: 'anongender' },
  { label: 'Antegender', value: 'antegender' },
  { label: 'Anxiegender', value: 'anxiegender' },
  { label: 'Apagender', value: 'apagender' },
  { label: 'Apconsugender', value: 'apconsugender' },
  { label: 'Astergender', value: 'astergender' },
  { label: 'Astralgender', value: 'astralgender' },
  { label: 'Autogender', value: 'autogender' },
  { label: 'Axigender', value: 'axigender' },
  { label: 'Bigender', value: 'bigender' },
  { label: 'Biogender', value: 'biogender' },
  { label: 'Blurgender', value: 'blurgender' },
  { label: 'Boyflux', value: 'boyflux' },
  { label: 'Burstgender', value: 'burstgender' },
  { label: 'Caelgender', value: 'caelgender' },
  { label: 'Cassgender', value: 'cassgender' },
  { label: 'Cassflux', value: 'cassflux' },
  { label: 'Cavusgender', value: 'cavusgender' },
  { label: 'Cendgender', value: 'cendgender' },
  { label: 'Ceterofluid', value: 'ceterofluid' },
  { label: 'Ceterogender', value: 'ceterogender' },
  { label: 'Cis', value: 'cis' },
  { label: 'Cisgender', value: 'cisgender' },
  { label: 'Cis Female', value: 'cis_female' },
  { label: 'Cis Male', value: 'cis_male' },
  { label: 'Cis Man', value: 'cis_man' },
  { label: 'Cis Woman', value: 'cis_woman' },
  { label: 'Cisgender Female', value: 'cisgender_female' },
  { label: 'Cisgender Male', value: 'cisgender_male' },
  { label: 'Cisgender Man', value: 'cisgender_man' },
  { label: 'Cisgender Woman', value: 'cisgender_woman' },
  { label: 'Cloudgender', value: 'cloudgender' },
  { label: 'Collgender', value: 'collgender' },
  { label: 'Colorgender', value: 'colorgender' },
  { label: 'Commogender', value: 'commogender' },
  { label: 'Condigender', value: 'condigender' },
  { label: 'Deliciagender', value: 'deliciagender' },
  { label: 'Demifluid', value: 'demifluid' },
  { label: 'Demiflux', value: 'demiflux' },
  { label: 'Demigender', value: 'demigender' },
  { label: 'Domgender', value: 'domgender' },
  { label: 'Duragender', value: 'duragender' },
  { label: 'Egogender', value: 'egogender' },
  { label: 'Epicene', value: 'epicene' },
  { label: 'Espigender', value: 'espigender' },
  { label: 'Exgender', value: 'exgender' },
  { label: 'Existigender', value: 'existigender' },
  { label: 'Female to Male', value: 'male' },
  { label: 'Femfluid', value: 'femfluid' },
  { label: 'Femgender', value: 'femgender' },
  { label: 'Fluidflux', value: 'fluidflux' },
  { label: 'FTM', value: 'ftm' },
  { label: 'Gemigender', value: 'gemigender' },
  { label: 'Genderblank', value: 'genderblank' },
  { label: 'Genderflow', value: 'genderflow' },
  { label: 'Genderfluid', value: 'genderfluid' },
  { label: 'Genderflux', value: 'genderflux' },
  { label: 'Genderfuzz', value: 'genderfuzz' },
  { label: 'Gender Neutral', value: 'gender_neutral' },
  { label: 'Gender Nonconforming', value: 'gender_nonconforming' },
  { label: 'Genderpunk', value: 'genderpunk' },
  { label: 'Genderqueer', value: 'genderqueer' },
  { label: 'Gender Questioning', value: 'gender_questioning' },
  { label: 'Gender Variant', value: 'gender_variant' },
  { label: 'Genderwitched', value: 'genderwitched' },
  { label: 'Girlflux', value: 'girlflux' },
  { label: 'Glassgender', value: 'glassgender' },
  { label: 'Glimragender', value: 'glimragender' },
  { label: 'Greygender', value: 'greygender' },
  { label: 'Gyragender', value: 'gyragender' },
  { label: 'Healgender', value: 'healgender' },
  { label: 'Heliogender', value: 'heliogender' },
  { label: 'Hemigender', value: 'hemigender' },
  { label: 'Horogender', value: 'horogender' },
  { label: 'Hydrogender', value: 'hydrogender' },
  { label: 'Imperigender', value: 'imperigender' },
  { label: 'Intergender', value: 'intergender' },
  { label: 'Juxera', value: 'juxera' },
  { label: 'Libragender', value: 'libragender' },
  { label: 'Magigender', value: 'magigender' },
  { label: 'Male to Female', value: 'male_to_female' },
  { label: 'Mascfluid', value: 'mascfluid' },
  { label: 'Mascgender', value: 'mascgender' },
  { label: 'Maverique', value: 'maverique' },
  { label: 'Mirrorgender', value: 'mirrorgender' },
  { label: 'Molligender', value: 'molligender' },
  { label: 'Multigender', value: 'multigender' },
  { label: 'MTF', value: 'mtf' },
  { label: 'Nanogender', value: 'nanogender' },
  { label: 'Neither', value: 'neither' },
  { label: 'Neutrois', value: 'neutrois' },
  { label: 'Non-binary', value: 'non_binary' },
  { label: 'Omnigender', value: 'omnigender' },
  { label: 'Oneirogender', value: 'oneirogender' },
  { label: 'Other', value: 'other' },
  { label: 'Pangender', value: 'pangender' },
  { label: 'Paragender', value: 'paragender' },
  { label: 'Perigender', value: 'perigender' },
  { label: 'Polygender', value: 'polygender' },
  { label: 'Proxvir', value: 'proxvir' },
  { label: 'Quoigender', value: 'quoigender' },
  { label: 'Subgender', value: 'subgender' },
  { label: 'Surgender', value: 'surgender' },
  { label: 'Systemgender', value: 'systemgender' },
  { label: 'Tragender', value: 'tragender' },
  { label: 'Trans', value: 'trans' },
  { label: 'Trans*', value: 'trans*' },
  { label: 'Trans Female', value: 'trans_female' },
  { label: 'Trans* Female', value: 'trans*_female' },
  { label: 'Trans Male', value: 'trans_male' },
  { label: 'Trans* Male', value: 'trans*_male' },
  { label: 'Trans Man', value: 'trans_man' },
  { label: 'Trans* Man', value: 'trans_man' },
  { label: 'Trans Person', value: 'trans_person' },
  { label: 'Trans* Person', value: 'trans*_person' },
  { label: 'Trans Woman', value: 'woman' },
  { label: 'Trans* Woman', value: 'woman' },
  { label: 'Transfeminine', value: 'transfeminine' },
  { label: 'Transgender', value: 'transgender' },
  { label: 'Transgender Female', value: 'transgender_female' },
  { label: 'Transgender Male', value: 'transgender_male' },
  { label: 'Transgender Man', value: 'transgender_man' },
  { label: 'Transgender Person', value: 'transgender_person' },
  { label: 'Transgender Woman', value: 'transgender_woman' },
  { label: 'Transmasculine', value: 'transmasculine' },
  { label: 'Transsexual', value: 'transsexual' },
  { label: 'Transsexual Female', value: 'transsexual_female' },
  { label: 'Transsexual Male', value: 'transsexual_male' },
  { label: 'Transsexual Man', value: 'transsexual_man' },
  { label: 'Transsexual Person', value: 'transsexual_person' },
  { label: 'Transsexual Woman', value: 'transsexual_woman' },
  { label: 'Trigender', value: 'trigender' },
  { label: 'Two-Spirit', value: 'spirit' },
  { label: 'Vapogender', value: 'vapogender' },
  { label: 'Venngender', value: 'venngender' },
  { label: 'Verangender', value: 'verangender' },
  { label: 'Vibragender', value: 'vibragender' },
  { label: 'Vocigender', value: 'vocigender' },
];
