export const sexualities = [
  { label: 'Straight', value: 'straight' },
  { label: 'Gay', value: 'gay' },
  { label: 'Lesbian', value: 'lesbian' },
  { label: 'Bisexual', value: 'bisexual' },
  { label: 'Pansexual', value: 'pansexual' },
  { label: 'Asexual', value: 'asexual' },
  { label: 'Queer', value: 'queer' },
  { label: 'Demisexual', value: 'demisexual' },
  { label: 'Heteroflexible', value: 'heteroflexible' },
  { label: 'Homoflexible', value: 'homoflexible' },
  { label: 'Sapiosexual', value: 'sapiosexual' },
  { label: 'Polysexual', value: 'polysexual' },
  { label: 'Omnisexual', value: 'omnisexual' },
  { label: 'Graysexual', value: 'graysexual' },
  { label: 'Skoliosexual', value: 'skoliosexual' },
  { label: 'Androgynosexual', value: 'androgynosexual' },
  { label: 'Allosexual', value: 'allosexual' },
  { label: 'Autosexual', value: 'autosexual' },
  { label: 'Reciprosexual', value: 'reciprosexual' },
  { label: 'Questioning', value: 'questioning' },
];
