-- Insert roles
INSERT INTO user_role_types (id, name) VALUES (1, 'ROLE_USER');
INSERT INTO user_role_types (id, name) VALUES (2, 'ROLE_MODERATOR');
INSERT INTO user_role_types (id, name) VALUES (3, 'ROLE_ADMIN');

-- Insert genders
INSERT INTO user_gender_types (id, name) VALUES (1, 'MALE');
INSERT INTO user_gender_types (id, name) VALUES (2, 'FEMALE');
INSERT INTO user_gender_types (id, name) VALUES (3, 'OTHER');

-- Insert connection types
INSERT INTO connection_types (id, name) VALUES (1, 'SEEN');
INSERT INTO connection_types (id, name) VALUES (2, 'OPENED_PROFILE');
INSERT INTO connection_types (id, name) VALUES (3, 'JUST_FRIENDS');
INSERT INTO connection_types (id, name) VALUES (4, 'MAYBE_MORE');
INSERT INTO connection_types (id, name) VALUES (5, 'BLOCKED');
INSERT INTO connection_types (id, name) VALUES (6, 'PENDING');

-- Insert message event types
INSERT INTO message_event_types (id, name) VALUES (1, 'SENT');
INSERT INTO message_event_types (id, name) VALUES (2, 'RECEIVED');
INSERT INTO message_event_types (id, name) VALUES (3, 'READ');

-- Insert activity log types
INSERT INTO activity_log_types (id, name) VALUES (1, 'CREATED');
INSERT INTO activity_log_types (id, name) VALUES (2, 'VERIFIED');
INSERT INTO activity_log_types (id, name) VALUES (3, 'LOGIN');
INSERT INTO activity_log_types (id, name) VALUES (4, 'LOGOUT');

-- Insert attribute change types
INSERT INTO attribute_change_types (id, name) VALUES (1, 'CREATED');
INSERT INTO attribute_change_types (id, name) VALUES (2, 'GENDER');
INSERT INTO attribute_change_types (id, name) VALUES (3, 'BIRTHDATE');
INSERT INTO attribute_change_types (id, name) VALUES (4, 'LOCATION');

-- Insert preference change types
INSERT INTO preference_change_types (id, name) VALUES (1, 'CREATED');
INSERT INTO preference_change_types (id, name) VALUES (2, 'GENDER');
INSERT INTO preference_change_types (id, name) VALUES (3, 'AGE_MIN');
INSERT INTO preference_change_types (id, name) VALUES (4, 'AGE_MAX');
INSERT INTO preference_change_types (id, name) VALUES (5, 'DISTANCE');
INSERT INTO preference_change_types (id, name) VALUES (6, 'TOLERANCE');

-- Insert profile change types
INSERT INTO profile_change_types (id, name) VALUES (1, 'CREATED');
INSERT INTO profile_change_types (id, name) VALUES (2, 'AGE');
INSERT INTO profile_change_types (id, name) VALUES (3, 'BIO');
INSERT INTO profile_change_types (id, name) VALUES (4, 'PHOTO');
INSERT INTO profile_change_types (id, name) VALUES (5, 'INTERESTS');

-- Insert user state types
INSERT INTO user_state_types (id, name) VALUES (1, 'UNVERIFIED');
INSERT INTO user_state_types (id, name) VALUES (2, 'VERIFIED');
INSERT INTO user_state_types (id, name) VALUES (3, 'NEW');
INSERT INTO user_state_types (id, name) VALUES (4, 'ACTIVE');
INSERT INTO user_state_types (id, name) VALUES (5, 'PENDING');
INSERT INTO user_state_types (id, name) VALUES (6, 'SUSPENDED');
INSERT INTO user_state_types (id, name) VALUES (7, 'DORMANT');
INSERT INTO user_state_types (id, name) VALUES (8, 'DISABLED');

-- Insert hobby categories
INSERT INTO hobby (id, name, category, sub_category) VALUES (1, '3D printing', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (2, 'Acrobatics', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (3, 'Acting', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (4, 'Amateur radio', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (5, 'Animation', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (6, 'Aquascaping', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (7, 'Astrology', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (8, 'Astronomy', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (9, 'Baking', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (10, 'Baton twirling', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (11, 'Blogging', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (12, 'Building', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (13, 'Board/tabletop games', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (14, 'Book discussion clubs', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (15, 'Book restoration', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (16, 'Bowling', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (17, 'Brazilian jiu-jitsu', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (18, 'Breadmaking', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (19, 'Bullet journaling', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (20, 'Cabaret', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (21, 'Calligraphy', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (22, 'Candle making', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (23, 'Candy making', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (24, 'Car fixing & building', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (25, 'Card games', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (26, 'Cheesemaking', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (27, 'Cleaning', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (28, 'Clothesmaking', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (29, 'Coffee roasting', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (30, 'Collecting', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (31, 'Coloring', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (32, 'Computer programming', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (33, 'Confectionery', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (34, 'Cooking', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (35, 'Cosplaying', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (36, 'Couponing', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (37, 'Craft', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (38, 'Creative writing', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (39, 'Crocheting', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (40, 'Cross-stitch', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (41, 'Crossword puzzles', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (42, 'Cryptography', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (43, 'Cue sports', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (44, 'Dance', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (45, 'Digital arts', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (46, 'Distro Hopping', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (47, 'DJing', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (48, 'Do it yourself', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (49, 'Drama', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (50, 'Drawing', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (51, 'Drink mixing', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (52, 'Drinking', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (53, 'Electronic games', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (54, 'Electronics', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (55, 'Embroidery', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (56, 'Experimenting', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (57, 'Fantasy sports', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (58, 'Fashion', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (59, 'Fashion design', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (60, 'Fishkeeping', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (61, 'Filmmaking', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (62, 'Flower arranging', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (63, 'Fly tying', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (64, 'Foreign language learning', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (65, 'Furniture building', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (66, 'Gaming', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (67, 'Genealogy', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (68, 'Gingerbread house making', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (69, 'Glassblowing', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (70, 'Graphic design', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (71, 'Gunsmithing', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (72, 'Gymnastics', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (73, 'Hacking', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (74, 'Herp keeping', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (75, 'Home improvement', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (76, 'Homebrewing', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (77, 'Houseplant care', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (78, 'Hula hooping', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (79, 'Humor', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (80, 'Hydroponics', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (81, 'Ice skating', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (82, 'Jewelry making', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (83, 'Jigsaw puzzles', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (84, 'Journaling', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (85, 'Juggling', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (86, 'Karaoke', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (87, 'Karate', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (88, 'Kendama', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (89, 'Knife making', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (90, 'Knitting', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (91, 'Knot tying', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (92, 'Kombucha brewing', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (93, 'Lace making', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (94, 'Lapidary', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (95, 'Leather crafting', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (96, 'Lego building', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (97, 'Lock picking', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (98, 'Listening to music', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (99, 'Listening to podcasts', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (100, 'Machining', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (101, 'Macrame', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (102, 'Magic', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (103, 'Makeup', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (104, 'Mazes (indoor/outdoor)', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (105, 'Metalworking', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (106, 'Model building', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (107, 'Model engineering', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (108, 'Nail art', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (109, 'Needlepoint', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (110, 'Origami', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (111, 'Painting', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (112, 'Palmistry', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (113, 'Pet adoption & fostering', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (114, 'Philately', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (115, 'Photography', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (116, 'Practical jokes', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (117, 'Pressed flower craft', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (118, 'Playing musical instruments', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (119, 'Poi', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (120, 'Pottery', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (121, 'Powerlifting', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (122, 'Puzzles', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (123, 'Quilling', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (124, 'Quilting', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (125, 'Quizzes', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (126, 'Radio-controlled model', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (127, 'Rail transport modeling', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (128, 'Rapping', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (129, 'Reading', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (130, 'Refinishing', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (131, 'Reiki', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (132, 'Robot combat', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (133, 'Rubik''s Cube', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (134, 'Scrapbooking', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (135, 'Sculpting', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (136, 'Sewing', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (137, 'Shoemaking', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (138, 'Singing', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (139, 'Sketching', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (140, 'Skipping rope', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (141, 'Slot car', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (142, 'Soapmaking', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (143, 'Social media', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (144, 'Spreadsheets', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (145, 'Stand-up comedy', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (146, 'Stamp collecting', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (147, 'Table tennis', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (148, 'Tarot', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (149, 'Taxidermy', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (150, 'Thrifting', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (151, 'Video editing', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (152, 'Video game developing', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (153, 'Video gaming', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (154, 'Watching movies', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (155, 'Watching television', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (156, 'Videography', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (157, 'Virtual reality', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (158, 'Waxing', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (159, 'Weaving', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (160, 'Weight training', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (161, 'Welding', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (162, 'Whittling', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (163, 'Wikipedia editing', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (164, 'Winemaking', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (165, 'Wood carving', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (166, 'Woodworking', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (167, 'Worldbuilding', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (168, 'Writing', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (169, 'Word searches', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (170, 'Yo-yoing', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (171, 'Yoga', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (172, 'Zumba', 'General', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (173, 'Amusement park visiting', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (174, 'Air sports', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (175, 'Airsoft', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (176, 'Amateur geology', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (177, 'Archery', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (178, 'Astronomy', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (179, 'Backpacking', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (180, 'Badminton', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (181, 'BASE jumping', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (182, 'Baseball', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (183, 'Basketball', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (184, 'Beekeeping', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (185, 'Birdwatching', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (186, 'Blacksmithing', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (187, 'BMX', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (188, 'Board sports', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (189, 'Bodybuilding', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (190, 'Bonsai', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (191, 'Butterfly watching', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (192, 'Bus riding', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (193, 'Camping', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (194, 'Canoeing', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (195, 'Canyoning', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (196, 'Car riding', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (197, 'Caving', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (198, 'Composting', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (199, 'Cycling', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (200, 'Dowsing', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (201, 'Driving', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (202, 'Farming', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (203, 'Fishing', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (204, 'Flag football', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (205, 'Flower growing', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (206, 'Flying', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (207, 'Flying disc', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (208, 'Foraging', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (209, 'Fossicking', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (210, 'Freestyle football', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (211, 'Gardening', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (212, 'Geocaching', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (213, 'Ghost hunting', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (214, 'Gold prospecting', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (215, 'Graffiti', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (216, 'Handball', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (217, 'Herbalism', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (218, 'Herping', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (219, 'High-power rocketry', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (220, 'Hiking', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (221, 'Hobby horsing', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (222, 'Hobby tunneling', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (223, 'Hooping', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (224, 'Horseback riding', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (225, 'Hunting', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (226, 'Inline skating', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (227, 'Jogging', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (228, 'Jumping rope', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (229, 'Kayaking', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (230, 'Kite flying', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (231, 'Kitesurfing', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (232, 'Lacrosse', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (233, 'LARPing', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (234, 'Letterboxing', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (235, 'Longboarding', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (236, 'Martial arts', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (237, 'Metal detecting', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (238, 'Meteorology', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (239, 'Motor sports', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (240, 'Mountain biking', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (241, 'Mountaineering', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (242, 'Museum visiting', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (243, 'Mushroom hunting', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (244, 'Netball', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (245, 'Nordic skating', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (246, 'Orienteering', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (247, 'Paintball', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (248, 'Parkour', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (249, 'Photography', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (250, 'Podcast hosting', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (251, 'Polo', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (252, 'Public transport riding', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (253, 'Rafting', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (254, 'Railway journeys', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (255, 'Rappelling', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (256, 'Road biking', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (257, 'Rock climbing', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (258, 'Roller skating', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (259, 'Rugby', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (260, 'Running', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (261, 'Radio-controlled model', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (262, 'Sailing', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (263, 'Sand art', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (264, 'Scouting', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (265, 'Scuba diving', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (266, 'Sculling', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (267, 'Shooting', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (268, 'Shopping', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (269, 'Shuffleboard', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (270, 'Skateboarding', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (271, 'Skiing', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (272, 'Skimboarding', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (273, 'Skydiving', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (274, 'Slacklining', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (275, 'Snowboarding', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (276, 'Snowmobiling', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (277, 'Snowshoeing', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (278, 'Soccer', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (279, 'Stone skipping', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (280, 'Sun bathing', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (281, 'Surfing', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (282, 'Survivalism', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (283, 'Swimming', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (284, 'Taekwondo', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (285, 'Tai chi', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (286, 'Tennis', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (287, 'Topiary', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (288, 'Tourism', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (289, 'Thru-hiking', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (290, 'Trade fair visiting', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (291, 'Travel', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (292, 'Urban exploration', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (293, 'Vacation', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (294, 'Vegetable farming', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (295, 'Videography', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (296, 'Vehicle restoration', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (297, 'Walking', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (298, 'Water sports', 'General', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (299, 'Astronomy', 'Educational', '');
INSERT INTO hobby (id, name, category, sub_category) VALUES (300, 'Biology', 'Educational', '');
INSERT INTO hobby (id, name, category, sub_category) VALUES (301, 'Chemistry', 'Educational', '');
INSERT INTO hobby (id, name, category, sub_category) VALUES (302, 'Electrochemistry', 'Educational', '');
INSERT INTO hobby (id, name, category, sub_category) VALUES (303, 'Physics', 'Educational', '');
INSERT INTO hobby (id, name, category, sub_category) VALUES (304, 'Psychology', 'Educational', '');
INSERT INTO hobby (id, name, category, sub_category) VALUES (305, 'Sports science', 'Educational', '');
INSERT INTO hobby (id, name, category, sub_category) VALUES (306, 'Geography', 'Educational', '');
INSERT INTO hobby (id, name, category, sub_category) VALUES (307, 'History', 'Educational', '');
INSERT INTO hobby (id, name, category, sub_category) VALUES (308, 'Mathematics', 'Educational', '');
INSERT INTO hobby (id, name, category, sub_category) VALUES (309, 'Railway studies', 'Educational', '');
INSERT INTO hobby (id, name, category, sub_category) VALUES (310, 'Action figure', 'Collection', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (311, 'Antiquing', 'Collection', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (312, 'Ant-keeping', 'Collection', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (313, 'Art collecting', 'Collection', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (314, 'Book collecting', 'Collection', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (315, 'Button collecting', 'Collection', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (316, 'Cartophily', 'Collection', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (317, 'Coin collecting', 'Collection', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (318, 'Comic book collecting', 'Collection', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (319, 'Deltiology', 'Collection', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (320, 'Die-cast toy', 'Collection', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (321, 'Digital hoarding', 'Collection', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (322, 'Dolls', 'Collection', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (323, 'Element collecting', 'Collection', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (324, 'Ephemera collecting', 'Collection', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (325, 'Fusilately', 'Collection', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (326, 'Knife collecting', 'Collection', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (327, 'Lotology', 'Collection', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (329, 'Fingerprint collecting', 'Collection', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (330, 'Perfume', 'Collection', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (331, 'Phillumeny', 'Collection', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (332, 'Radio-controlled model', 'Collection', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (333, 'Rail transport modelling', 'Collection', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (334, 'Record collecting', 'Collection', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (335, 'Rock tumbling', 'Collection', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (336, 'Scutelliphily', 'Collection', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (337, 'Shoes', 'Collection', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (338, 'Slot car', 'Collection', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (339, 'Sports memorabilia', 'Collection', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (340, 'Stamp collecting', 'Collection', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (341, 'Stuffed toy collecting', 'Collection', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (342, 'Tea bag collecting', 'Collection', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (343, 'Ticket collecting', 'Collection', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (344, 'Toys', 'Collection', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (345, 'Transit map collecting', 'Collection', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (346, 'Video game collecting', 'Collection', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (347, 'Vintage cars', 'Collection', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (348, 'Vintage clothing', 'Collection', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (349, 'Vinyl Records', 'Collection', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (350, 'Antiquities', 'Collection', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (351, 'Auto audiophilia', 'Collection', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (352, 'Flower collecting and pressing', 'Collection', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (353, 'Fossil hunting', 'Collection', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (354, 'Insect collecting', 'Collection', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (355, 'Magnet fishing', 'Collection', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (356, 'Metal detecting', 'Collection', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (357, 'Mineral collecting', 'Collection', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (358, 'Rock balancing', 'Collection', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (359, 'Sea glass collecting', 'Collection', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (360, 'Seashell collecting', 'Collection', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (361, 'Stone collecting', 'Collection', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (362, 'Animal fancy', 'Competitive', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (363, 'Axe throwing', 'Competitive', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (364, 'Backgammon', 'Competitive', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (365, 'Badminton', 'Competitive', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (366, 'Baton twirling', 'Competitive', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (367, 'Beauty pageants', 'Competitive', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (368, 'Billiards', 'Competitive', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (369, 'Bowling', 'Competitive', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (370, 'Boxing', 'Competitive', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (371, 'Bridge', 'Competitive', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (372, 'Checkers (draughts)', 'Competitive', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (373, 'Cheerleading', 'Competitive', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (374, 'Chess', 'Competitive', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (375, 'Color guard', 'Competitive', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (376, 'Cribbage', 'Competitive', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (377, 'Curling', 'Competitive', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (378, 'Dancing', 'Competitive', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (379, 'Darts', 'Competitive', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (380, 'Debate', 'Competitive', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (381, 'Dominoes', 'Competitive', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (382, 'Eating', 'Competitive', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (383, 'Esports', 'Competitive', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (384, 'Fencing', 'Competitive', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (385, 'Go', 'Competitive', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (386, 'Gymnastics', 'Competitive', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (387, 'Ice hockey', 'Competitive', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (388, 'Ice skating', 'Competitive', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (389, 'Judo', 'Competitive', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (390, 'Jujitsu', 'Competitive', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (391, 'Kabaddi', 'Competitive', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (392, 'Knowledge/word games', 'Competitive', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (393, 'Laser tag', 'Competitive', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (394, 'Longboarding', 'Competitive', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (395, 'Mahjong', 'Competitive', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (396, 'Marbles', 'Competitive', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (397, 'Martial arts', 'Competitive', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (398, 'Model United Nations', 'Competitive', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (399, 'Poker', 'Competitive', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (400, 'Pool', 'Competitive', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (401, 'Role-playing games', 'Competitive', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (402, 'Shogi', 'Competitive', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (403, 'Slot car racing', 'Competitive', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (404, 'Speedcubing', 'Competitive', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (405, 'Sport stacking', 'Competitive', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (406, 'Table football', 'Competitive', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (407, 'Table tennis', 'Competitive', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (408, 'Volleyball', 'Competitive', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (409, 'Weightlifting', 'Competitive', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (410, 'Wrestling', 'Competitive', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (411, 'Airsoft', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (412, 'Archery', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (413, 'Association football', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (414, 'Australian rules football', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (415, 'Auto racing', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (416, 'Baseball', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (417, 'Beach volleyball', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (418, 'Breakdancing', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (419, 'Climbing', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (420, 'Cricket', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (421, 'Croquet', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (422, 'Cycling', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (423, 'Disc golf', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (424, 'Dog sport', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (425, 'Equestrianism', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (426, 'Exhibition drill', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (427, 'Field hockey', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (428, 'Figure skating', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (429, 'Fishing', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (430, 'Footbag', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (431, 'Frisbee', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (432, 'Golfing', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (433, 'Handball', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (434, 'Horseback riding', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (435, 'Horseshoes', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (436, 'Iceboat racing', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (437, 'Jukskei', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (438, 'Kart racing', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (439, 'Knife throwing', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (440, 'Lacrosse', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (441, 'Longboarding', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (442, 'Long-distance running', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (443, 'Marching band', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (444, 'Model aircraft', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (445, 'Orienteering', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (446, 'Pickleball', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (447, 'Quidditch', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (448, 'Race walking', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (449, 'Racquetball', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (450, 'Radio-controlled car racing', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (451, 'Roller derby', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (452, 'Rugby league football', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (453, 'Sculling', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (454, 'Shooting sport', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (455, 'Skateboarding', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (456, 'Skiing', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (457, 'Sled dog racing', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (458, 'Softball', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (459, 'Speed skating', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (460, 'Squash', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (461, 'Surfing', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (462, 'Swimming', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (463, 'Table tennis', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (464, 'Tennis', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (465, 'Tennis polo', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (466, 'Tether car', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (467, 'Tour skating', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (468, 'Tourism', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (469, 'Trapshooting', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (470, 'Triathlon', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (471, 'Ultimate frisbee', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (472, 'Volleyball', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (473, 'Water polo', 'Competitive', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (474, 'Fishkeeping', 'Observation', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (475, 'Learning', 'Observation', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (476, 'Meditation', 'Observation', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (477, 'Microscopy', 'Observation', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (478, 'Reading', 'Observation', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (479, 'Research', 'Observation', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (480, 'Shortwave listening', 'Observation', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (481, 'Audiophile', 'Observation', 'Indoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (482, 'Aircraft spotting', 'Observation', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (483, 'Amateur astronomy', 'Observation', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (484, 'Birdwatching', 'Observation', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (485, 'Bus spotting', 'Observation', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (486, 'Geocaching', 'Observation', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (487, 'Gongoozling', 'Observation', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (488, 'Herping', 'Observation', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (489, 'Hiking', 'Observation', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (490, 'Meteorology', 'Observation', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (491, 'Photography', 'Observation', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (492, 'Satellite watching', 'Observation', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (493, 'Trainspotting', 'Observation', 'Outdoors');
INSERT INTO hobby (id, name, category, sub_category) VALUES (494, 'Whale watching', 'Observation', 'Outdoors');

